Vagrant::Config.run do |config|
  config.vm.box = "gemstone"
  #config.vm.boot_mode = :gui

  # config.vm.network "33.33.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port("http",80,7778)
  config.vm.forward_port("gs64ldi", 50377, 50377)
  config.vm.forward_port("gemsession", 50378, 50378)


  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["cookbooks","site-cookbooks"]
     chef.add_recipe "virtual_gemstone::production"
  #   chef.add_role "web"
  end
end
